version: 2.1
executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01
jobs:
  lint:
    executor: ubuntu
    steps:
      - checkout
      - run: make install-tox
      - run: make dev
      - run: make lint
  test:
    executor: ubuntu
    steps:
      - checkout
      # virtualenv is broken on ubuntu if using liblzma and a few others (zlib, I belive)
      # Since we only need to support python 3.8 at the moment, I am going to run CI tests outside of
      # tox. This is not a permanent solution.
      #- run: make install-tox
      #- run: tox -e py38
      - run: sudo pip3 install -r requirements.txt
      - run: sudo pip3 install .
      - run: pytest
  publish-to-gemfury:
    executor: ubuntu
    steps:
      - checkout
      - run: ci/publish

workflows:
  version: 2
  primary:
    jobs:
      - lint:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
      - test:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
      - publish-to-gemfury:
          context: musekafka-publish
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
